/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocoRouteImport } from './routes/troco'
import { Route as RepetidasRouteImport } from './routes/repetidas'
import { Route as QueroRouteImport } from './routes/quero'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AlbumRouteImport } from './routes/album'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTrocoRouteImport } from './routes/api/troco'
import { Route as ApiQueroRouteImport } from './routes/api/quero'
import { Route as ApiLogoutRouteImport } from './routes/api/logout'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiControleRouteImport } from './routes/api/controle'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCadastroRouteImport } from './routes/api/cadastro'

const TrocoRoute = TrocoRouteImport.update({
  id: '/troco',
  path: '/troco',
  getParentRoute: () => rootRouteImport,
} as any)
const RepetidasRoute = RepetidasRouteImport.update({
  id: '/repetidas',
  path: '/repetidas',
  getParentRoute: () => rootRouteImport,
} as any)
const QueroRoute = QueroRouteImport.update({
  id: '/quero',
  path: '/quero',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumRoute = AlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrocoRoute = ApiTrocoRouteImport.update({
  id: '/api/troco',
  path: '/api/troco',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueroRoute = ApiQueroRouteImport.update({
  id: '/api/quero',
  path: '/api/quero',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiControleRoute = ApiControleRouteImport.update({
  id: '/api/controle',
  path: '/api/controle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCadastroRoute = ApiCadastroRouteImport.update({
  id: '/api/cadastro',
  path: '/api/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/cadastro': typeof CadastroRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/quero': typeof QueroRoute
  '/repetidas': typeof RepetidasRoute
  '/troco': typeof TrocoRoute
  '/api/cadastro': typeof ApiCadastroRoute
  '/api/chat': typeof ApiChatRoute
  '/api/controle': typeof ApiControleRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/quero': typeof ApiQueroRoute
  '/api/troco': typeof ApiTrocoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/cadastro': typeof CadastroRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/quero': typeof QueroRoute
  '/repetidas': typeof RepetidasRoute
  '/troco': typeof TrocoRoute
  '/api/cadastro': typeof ApiCadastroRoute
  '/api/chat': typeof ApiChatRoute
  '/api/controle': typeof ApiControleRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/quero': typeof ApiQueroRoute
  '/api/troco': typeof ApiTrocoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/cadastro': typeof CadastroRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/quero': typeof QueroRoute
  '/repetidas': typeof RepetidasRoute
  '/troco': typeof TrocoRoute
  '/api/cadastro': typeof ApiCadastroRoute
  '/api/chat': typeof ApiChatRoute
  '/api/controle': typeof ApiControleRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/quero': typeof ApiQueroRoute
  '/api/troco': typeof ApiTrocoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/album'
    | '/cadastro'
    | '/chat'
    | '/login'
    | '/quero'
    | '/repetidas'
    | '/troco'
    | '/api/cadastro'
    | '/api/chat'
    | '/api/controle'
    | '/api/login'
    | '/api/logout'
    | '/api/quero'
    | '/api/troco'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/album'
    | '/cadastro'
    | '/chat'
    | '/login'
    | '/quero'
    | '/repetidas'
    | '/troco'
    | '/api/cadastro'
    | '/api/chat'
    | '/api/controle'
    | '/api/login'
    | '/api/logout'
    | '/api/quero'
    | '/api/troco'
  id:
    | '__root__'
    | '/'
    | '/album'
    | '/cadastro'
    | '/chat'
    | '/login'
    | '/quero'
    | '/repetidas'
    | '/troco'
    | '/api/cadastro'
    | '/api/chat'
    | '/api/controle'
    | '/api/login'
    | '/api/logout'
    | '/api/quero'
    | '/api/troco'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumRoute: typeof AlbumRoute
  CadastroRoute: typeof CadastroRoute
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  QueroRoute: typeof QueroRoute
  RepetidasRoute: typeof RepetidasRoute
  TrocoRoute: typeof TrocoRoute
  ApiCadastroRoute: typeof ApiCadastroRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiControleRoute: typeof ApiControleRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  ApiQueroRoute: typeof ApiQueroRoute
  ApiTrocoRoute: typeof ApiTrocoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/troco': {
      id: '/troco'
      path: '/troco'
      fullPath: '/troco'
      preLoaderRoute: typeof TrocoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repetidas': {
      id: '/repetidas'
      path: '/repetidas'
      fullPath: '/repetidas'
      preLoaderRoute: typeof RepetidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quero': {
      id: '/quero'
      path: '/quero'
      fullPath: '/quero'
      preLoaderRoute: typeof QueroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album': {
      id: '/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/troco': {
      id: '/api/troco'
      path: '/api/troco'
      fullPath: '/api/troco'
      preLoaderRoute: typeof ApiTrocoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quero': {
      id: '/api/quero'
      path: '/api/quero'
      fullPath: '/api/quero'
      preLoaderRoute: typeof ApiQueroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/controle': {
      id: '/api/controle'
      path: '/api/controle'
      fullPath: '/api/controle'
      preLoaderRoute: typeof ApiControleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cadastro': {
      id: '/api/cadastro'
      path: '/api/cadastro'
      fullPath: '/api/cadastro'
      preLoaderRoute: typeof ApiCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumRoute: AlbumRoute,
  CadastroRoute: CadastroRoute,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  QueroRoute: QueroRoute,
  RepetidasRoute: RepetidasRoute,
  TrocoRoute: TrocoRoute,
  ApiCadastroRoute: ApiCadastroRoute,
  ApiChatRoute: ApiChatRoute,
  ApiControleRoute: ApiControleRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  ApiQueroRoute: ApiQueroRoute,
  ApiTrocoRoute: ApiTrocoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
